### ISSUE TITLE
 Definition file does not exists

### ISSUE THREAD

**Issue by aigenseer** [shopware/production#48]
Hello Delevoper team,

When I run the \<rootdir>/bin/build-administration.sh or \<rootdir>/bin/build-shopware.sh script, I always get this error " Definition file does not exists". See the error message below.
I have not found a solution to fix the error. Is this a general problem?

At first glance it seems to me that it is in the file
\<rootdir>/vendor/shopware/storefront/Resources/app/storefront/node_modules/@shopware-ag/webpack-plugin-injector/index.js

The environment variable
const projectRoot = process.env.PROJECT_ROOT || '';
not handed over. It is always empty.

`\<rootdir>/vendor/shopware/administration/Resources/app/administration/node_modules/@shopware-ag/webpack-plugin-injector/index.js:128
            throw new Error('Definition file does not exists');
            ^

Error: Definition file does not exists
    at WebpackPluginInjector.getPluginDefinitionContent (\<rootdir>/vendor/shopware/administration/Resources/app/administration/node_modules/@shopware-ag/webpack-plugin-injector/index.js:128:19)
    at new WebpackPluginInjector (\<rootdir>/vendor/shopware/administration/Resources/app/administration/node_modules/@shopware-ag/webpack-plugin-injector/index.js:81:28)
    at Object.<anonymous> (\<rootdir>/vendor/shopware/administration/Resources/app/administration/build/webpack.prod.conf.js:67:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (\<rootdir>/vendor/shopware/administration/Resources/app/administration/build/build.js:11:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

**Comment by shyim** [comment]
Is fixed in meanwhile
